### PR TITLE
Stop at breakpoint / Continue if stopped

### LINKED ISSUE #23: Debugger - Continue
Continues the execution until it reaches a breakpoint or the execution ends. Depends on #18

### LINKED ISSUE #59: Debugger - Stop at breakpoint
This is not working in the current version, it only stops when you run it using step by step

### PR DESCRIPTION
**Pull request by meevee98**
fix #59 and fix #23

### CODE REVIEW

File: NeoDebuggerUI/ViewModels/InvokeWindowViewModel.cs [hunk 1]
```diff
@@ -188,35 +188,51 @@ public InvokeWindowViewModel()
...
+                    DebuggerStore.instance.manager.Run();
+                }
+                else
+                {
+                    DebuggerStore.instance.manager.RunSequence(SelectedTestSequence);
+                }
             }
 
-            if (result != null)
+            if (DebuggerStore.instance.manager.IsSteppingOrOnBreakpoint)
```
Comment (melanke) [inline NeoDebuggerUI/ViewModels/InvokeWindowViewModel.cs:211]: Why there is 2 if-elses checking the same thing? This clause must be re-checked after the first if? If so, put a comment explaining.

File: NeoDebuggerUI/ViewModels/MainWindowViewModel.cs [hunk 2]
```diff
@@ -139,6 +148,16 @@ public void ClearLog()
             Log = "";
         }
 
+        public void AddBreakpoints()
+        {
+            //test only
```
Comment (melanke) [inline NeoDebuggerUI/ViewModels/MainWindowViewModel.cs]: what do you mean by "test only"? Are you gonna remove this? If so, put a // TODO: <explain why you need to remove>
(TODO comments are easier to find on the IDE)

File: NeoDebuggerUI/Views/InvokeWindow.xaml.cs [hunk 3]
```diff
@@ -119,11 +122,11 @@ private void RegisterInteraction()
 
                 if (!UseTestSequence())
```
Comment (melanke) [inline NeoDebuggerUI/Views/InvokeWindow.xaml.cs]: Is this identation correct?
